// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5fCUFJhCqzRklsAsRmnILSF_k1c6F-i0',
    appId: '1:539358268875:web:5c16e4957c3f47338e3a4e',
    messagingSenderId: '539358268875',
    projectId: 'finalproject-7face',
    authDomain: 'finalproject-7face.firebaseapp.com',
    storageBucket: 'finalproject-7face.appspot.com',
    measurementId: 'G-5L48T13GTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBToSA9ubdpiV1aVPs8E5emutcfQajJdTs',
    appId: '1:539358268875:android:e7b1d561c181595d8e3a4e',
    messagingSenderId: '539358268875',
    projectId: 'finalproject-7face',
    storageBucket: 'finalproject-7face.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUeuD6rRaRCJWQebIDVlpvy3QAbjShYvM',
    appId: '1:539358268875:ios:b1421fe8a5884f168e3a4e',
    messagingSenderId: '539358268875',
    projectId: 'finalproject-7face',
    storageBucket: 'finalproject-7face.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUeuD6rRaRCJWQebIDVlpvy3QAbjShYvM',
    appId: '1:539358268875:ios:b1421fe8a5884f168e3a4e',
    messagingSenderId: '539358268875',
    projectId: 'finalproject-7face',
    storageBucket: 'finalproject-7face.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5fCUFJhCqzRklsAsRmnILSF_k1c6F-i0',
    appId: '1:539358268875:web:da552cd9eb9978808e3a4e',
    messagingSenderId: '539358268875',
    projectId: 'finalproject-7face',
    authDomain: 'finalproject-7face.firebaseapp.com',
    storageBucket: 'finalproject-7face.appspot.com',
    measurementId: 'G-L5F2HFJX7V',
  );
}
